name: 'Update Terraform Cloud Variable Set'
description: 'Invoke Terraform API to update Terraform variable set value'
inputs:
  organizationName:
    description: 'Terraform organization Name'
    required: true
  terraformToken:
    description: 'Terraform Token'
    required: true
  terraformHost:
    description: 'Terraform Host Name'
    default: 'app.terraform.io'
  variableSetName:
    description: 'The variable set key / name as shown in Terraform Cloud'
    required: true
  variableName:
    description: 'The variable key / name as shown in Terraform Cloud'
    required: true
  variableHCL:
    description: 'Specify true or false if variable should be in HCL format'
    default: false
    required: false
  variableValue:
    description: 'The variable value to be replaced in Terraform Cloud'
    required: true
outputs:
  variableId:
    description: 'The Updated Variable ID'
runs:
  using: 'node12'
  main: 'index.js'

branding:
  icon: 'play'  
  color: 'green'